debugEnable: true
reloadAllTree: false
removeEmptyVars: false
replace:
  - ["(UC\\d+_TR\\d+_)(UC\\d+_TR\\d+_)*", "$1", "TransactionController"]
  - ["(UC\\d+_)(UC\\d+_)*", "$1", "TestFragmentController"]

NodeProperties:
  TestFragmentController:
    search:
      - searchIn: ["#{name}", "(.*)"]
        searchOut: ["global.uc_name", "$1", "null"]
    template: "UC#{uc(,02)}_#{global.uc_name}"

  TransactionController:
    search:
      - searchIn: ["#{name}", "(.*)"]
        searchOut: ["global.step_name", "$1", "null"]
    template: "UC#{uc(get,02)}_TR#{tr(,02)}_#{global.step_name}"

  HTTPSamplerProxy:
    template: "UC#{uc(get,02)}_TR#{tr(get,02)}_RQ#{rq(,03)}_#{method}_#{path}"

variables: {}
counters:
  uc: {}
  tr:
    resetIf:
      - levelEquals: [1]
        nodeType: ["TestFragmentController"]
  rq:
    resetIf:
      - levelEquals: [2]
        nodeType: ["TransactionController"]
